# Generated by Django 4.2.4 on 2023-11-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reserva de Banho'},
        ),
    ]
