# Generated by Django 4.2.4 on 2023-12-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_petshop_alter_reserva_options_reserva_petshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshop',
            old_name='numero',
            new_name='numero_da_residencia',
        ),
    ]
