# Generated by Django 4.2.4 on 2023-11-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('data', models.DateField(help_text='dd/mm/yyyy', verbose_name='Data')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
