# Generated by Django 4.2.4 on 2023-11-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=255)),
                ('data_de_entrada', models.DateField(help_text='dd/mm/yyyy', verbose_name='Data')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('categoria_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.categoria')),
            ],
        ),
    ]
