# Generated by Django 4.2.4 on 2023-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=75, verbose_name='E-mail')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data Envio')),
                ('lido', models.BooleanField(blank=True, default=False, verbose_name='Lido')),
            ],
            options={
                'verbose_name': 'Formulario de Contato',
                'verbose_name_plural': 'Formularios de Contatos',
                'ordering': ['-data'],
            },
        ),
        migrations.DeleteModel(
            name='Reserva_pet',
        ),
    ]
